### ISSUE TITLE
NPM Project

### ISSUE THREAD

**Issue by vairamsvsjdo** [Arnoud-B/csscountrycodes#4]
Requesting for a new project with major version changes with the following features.
I will subsequently submit a pull request
- [] #4 Available as npm package
- [] #5 Fix style format issues
- [] #6 minimize file
- [] #3 Add license file
- [] #7 Add svg file version of image
- [] #8 Create svg css file
- [] #9 create JavaScript to make it available as a bootstrap component
